=== Igor-Gorchakov/mod-inventory/ramls/schema/compositeItem.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "item": {
      "type": "object",
      "$ref": "item.json"
    },
    "permanentLoanType": {
      "type": "object",
      "$ref": "loanType.json"
    },
    "temporaryLoanType": {
      "type": "object",
      "$ref": "loanType.json"
    },
    "materialType": {
      "type": "object",
      "$ref": "materialType.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "item"
  ]
}

=== Igor-Gorchakov/mod-inventory/ramls/examples/composite_item_get.json
{
  "item": {
    "id": "0b96a642-5e7f-452d-9cae-9cee66c9a892",
    "instanceId": "cf23adf0-61ba-4887-bf82-956c4aae2260",
    "title": "Uprooted",
    "barcode": "645398607547",
    "status": {
      "name" : "Available"
    },
    "materialTypeId": "fcf3d3dc-b27f-4ce4-a530-542ea53cacb5",
    "permanentLoanTypeId": "8e570d0d-931c-43d1-9ca1-221e693ea8d2",
    "temporaryLoanTypeId": "74c25903-4019-4d8a-9360-5cb7761f44e5",
    "location": {
      "name": "Main Library"
    }
  },
  "materialType": {
    "id": "fcf3d3dc-b27f-4ce4-a530-542ea53cacb5",
    "name": "Book"
  },
  "permanentLoanType": {
    "id": "8e570d0d-931c-43d1-9ca1-221e693ea8d2",
    "name": "Can Circulate"
  },
  "temporaryLoanType": {
    "id": "74c25903-4019-4d8a-9360-5cb7761f44e5",
    "name": "Course Reserve"
  }
}
